version: "3.8"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 994499_ma
      MYSQL_DATABASE: whisper
      MYSQL_USER: root
      MYSQL_PASSWORD: 994499_ma
    ports:
      - 3307:3306
    
    volumes: 
        - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080